services:
  martin:
    image: ghcr.io/maplibre/martin:latest
    command: ["--config", "/files/config.yaml"]           # this is the argument you pass in your `docker run`
    ports:
      - "3000:3000"
    volumes:
      - ./docker_files:/files

  mbtiles-maker:
    image: alex/mbtiles-maker:latest
    init: true
    volumes:  
      - ./docker_files:/files