services:
  martin:
    image: ghcr.io/maplibre/martin:latest
    command: ["--config", "/files/config.yaml"]
    ports:
      - "3000:3000"
    volumes:
      - ./docker_files:/files

  mbtiles-maker:
    image: alex/mbtiles-maker:latest
    init: true
    volumes:  
      - ./docker_files:/files
      - ./ev_router/data:/files/ev_router_data

  ors-app:
    image: openrouteservice/openrouteservice:latest
    container_name: ors
    ports:
      - "8080:8082"
    environment:
      CONTAINER_LOG_LEVEL: INFO
      REBUILD_GRAPHS: "False"
      ORS_CONFIG_LOCATION: /home/ors/config/ors-config.yml
      XMS: 4g
      XMX: 6g
    volumes:
      - ./ors/config:/home/ors/config
      - ./ors/files:/home/ors/files
      - ./ors/graphs:/home/ors/graphs
      - ./ors/logs:/home/ors/logs
      - ./ors/elevation_cache:/home/ors/elevation_cache