listen_addresses: 0.0.0.0:3000
base_path: /
cors: true

mbtiles:
  sources:
    tiles: /files/mbtiles/osm-2020-02-10-v3.11_europe.mbtiles
    chargers: /files/mbtiles/chargers.mbtiles

sprites:
  paths:
    - /files/sprites
    - /files/sdf_sprites

styles:
  sources:
   style: /files/style.json

fonts:
  - /files/fonts
